"""What a finished build tells a person (ADR-007).

A build used to end with three file paths. Whether it worked, what was
actually checked, what was *not* checked, who wrote the page and how many
tries it took were all there — spread over ``acceptance-report.json``,
``run.json``, ``task.json``, ``contract-warnings.json`` and one router log per
attempt. Reading them was a job.

:func:`collect` gathers them into one :class:`BuildSummary`, and three
renderers share it: ``report.html`` (self-contained, opens offline, the
screenshot inlined), a Markdown block for pull requests and issue comments,
and the terminal summary. One source means the three can never disagree.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from html import escape
from pathlib import Path
from typing import Any
import base64
import json
import os
import re

from . import __version__

REPORT_NAME = "report.html"

#: Chinese for every user-facing string. The key is the English text (or a
#: format template), so an untranslated string simply stays English.
_ZH = {
    "Works — every check passed": "可以用 —— 所有检查都通过了",
    "Does not work yet — some checks failed": "还不能用 —— 有检查没通过",
    "Stopped before it finished (interrupted)": "还没做完就被中断了",
    "Stopped at the time or cost budget": "到了时间或花费上限，先停下了",
    "Cancelled at plan review": "在审核计划时取消了",
    "Still running": "还在运行",
    "Files and safety": "文件与安全",
    "Makes no network requests": "不访问任何网络",
    "Every element the tests need is on the page": "测试需要的每个元素都在页面上",
    "A browser was available to test with": "找到了可用来测试的浏览器",
    "The page loaded and the test script ran": "页面能打开，测试脚本跑完了",
    "The test script reported back": "测试脚本返回了结果",
    "A screenshot was taken": "截图成功",
    "{file} exists": "{file} 存在",
    "the page": "页面",
    "Click {t}": "点击 {t}",
    "Type \u201c{v}\u201d into {t}": "在 {t} 输入\u201c{v}\u201d",
    "Wait {ms} ms": "等待 {ms} 毫秒",
    "{t} is on the page": "页面上有 {t}",
    "{t} shows \u201c{e}\u201d": "{t} 显示\u201c{e}\u201d",
    "{t} has {a} = \u201c{e}\u201d": "{t} 的 {a} 等于\u201c{e}\u201d",
    "No errors in the browser console": "浏览器控制台没有报错",
    "{p}/{t} checks passed": "{p}/{t} 项检查通过",
    "{n} attempt": "尝试 {n} 次",
    "{n} attempts": "尝试 {n} 次",
    "written by {w}": "由 {w} 编写",
    "{n} tokens": "{n} tokens",
    "What failed:": "哪里没通过：",
    "... and {n} more (see report.html)": "……还有 {n} 项（见 report.html）",
    "Not verified (a passing report does not cover these):": "没验证到的地方（通过了也不代表这些没问题）：",
    "Report:  ": "报告：  ",
    "Site:    ": "网页：  ",
    "Next:    ": "下一步：",
    "What it does": "功能",
    "What failed": "哪里没通过",
    "Not verified": "没验证到的地方",
    "Not verified — a passing report does not cover these:": "没验证到的地方 —— 通过了也不代表这些没问题：",
    "Every check": "全部检查",
    "Rainbow Octopus build report": "Rainbow Octopus 构建报告",
    "Open the page": "打开网页",
    "Next:": "下一步：",
    "What it should do": "应该做到的功能",
    "Goal": "目标",
    "What was checked": "检查了什么",
    "Attempts": "每次尝试",
    "Attempt": "次数",
    "Written by": "编写者",
    "Result": "结果",
    "Checks": "检查",
    "Time": "用时",
    "Cost": "花费",
    "Last problem": "最近的问题",
    "Browser console errors": "浏览器控制台报错",
    "Changes applied (revision {n})": "已应用的修改（第 {n} 版）",
    "These parts of the page were never observed changing, so a pass does not prove they work.":
        "测试从没看到这些部分发生变化，所以\u201c通过\u201d并不能证明它们能用。",
    "No checks have run yet.": "还没有运行任何检查。",
    "No attempts yet.": "还没有尝试。",
    "Generated by Rainbow Octopus {v}. This page works offline.": "由 Rainbow Octopus {v} 生成，这个页面可以离线打开。",
    "planner: {p}": "规划：{p}",
    "spent ${c}": "花费 ${c}",
    "updated {u} UTC": "更新于 {u} UTC",
    "passed": "通过",
    "checks failed": "检查未通过",
    "could not write the site": "没能写出网页",
    "written, not yet checked": "已写好，还没检查",
    "running": "进行中",
    "interrupted": "被中断",
    "internal error": "内部错误",
}


def detect_lang(text: str) -> str:
    """``zh`` when the idea is Chinese (or ROCTO_LANG=zh), otherwise ``en``."""
    forced = os.environ.get("ROCTO_LANG", "").strip().lower()
    if forced in {"zh", "en"}:
        return forced
    return "zh" if re.search(r"[\u4e00-\u9fff]", text or "") else "en"


_CONSTANT_WARNING = re.compile(
    r"^'(?P<id>[^']+)' is only ever asserted as '(?P<value>.*)'; no test observes it change"
)


def localize_warning(text: str, lang: str = "en") -> str:
    """Contract warnings are written in English by contract.py."""
    if lang != "zh":
        return text
    match = _CONSTANT_WARNING.match(text)
    if match:
        return (
            f"「{match['id']}」只被检查过等于「{match['value']}」，没有测试看到它变化，"
            "所以就算页面把这个值写死也能通过。"
        )
    return text


def tr(text: str, lang: str = "en", **values: Any) -> str:
    template = _ZH.get(text, text) if lang == "zh" else text
    return template.format(**values) if values else template


@dataclass
class CheckLine:
    name: str
    passed: bool
    detail: str
    #: Plain-language description of the step, when the spec says what it was.
    description: str = ""


@dataclass
class CheckGroup:
    title: str
    lines: list[CheckLine] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return all(line.passed for line in self.lines)


@dataclass
class BuildSummary:
    project_dir: Path
    idea: str = ""
    title: str = ""
    goal: str = ""
    features: list[str] = field(default_factory=list)
    phase: str = "unknown"
    passed: bool = False
    checks_passed: int = 0
    checks_total: int = 0
    groups: list[CheckGroup] = field(default_factory=list)
    console_errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    attempts: list[dict[str, Any]] = field(default_factory=list)
    planner: str | None = None
    cost_usd: float | None = None
    error: str | None = None
    screenshot: Path | None = None
    started_at: str = ""
    updated_at: str = ""
    revision: int = 0
    changes: list[str] = field(default_factory=list)
    tokens: int | None = None
    lang: str = "en"

    @property
    def verdict(self) -> str:
        if self.passed and self.phase == "completed":
            return "passed"
        if self.phase in {"interrupted", "stopped", "cancelled"}:
            return self.phase
        if self.phase in {"failed", "verification_failed", "execution_failed"}:
            return "failed"
        return "in progress"

    @property
    def headline(self) -> str:
        return tr({
            "passed": "Works — every check passed",
            "failed": "Does not work yet — some checks failed",
            "interrupted": "Stopped before it finished (interrupted)",
            "stopped": "Stopped at the time or cost budget",
            "cancelled": "Cancelled at plan review",
        }.get(self.verdict, "Still running"), self.lang)

    def next_step(self) -> str:
        path = _quote_path(self.project_dir)
        verdict = self.verdict
        if verdict == "passed":
            return f"rocto open {path}"
        if verdict == "cancelled":
            return "rocto build \"<idea>\" --review-plan"
        return f"rocto resume {path}"


def collect(project_dir: Path) -> BuildSummary:
    project_dir = Path(project_dir)
    internal = project_dir / ".rocto"
    state = _read_json(internal / "run.json") or {}
    spec = _read_json(internal / "task.json") or {}
    acceptance = _read_json(project_dir / "acceptance-report.json") or {}
    warnings = (_read_json(internal / "contract-warnings.json") or {}).get("warnings", [])

    checks = acceptance.get("checks", []) if isinstance(acceptance, dict) else []
    screenshot = project_dir / "screenshot.png"
    lang = detect_lang(str(state.get("idea", "")))
    summary = BuildSummary(
        project_dir=project_dir,
        idea=str(state.get("idea", "")),
        title=str(spec.get("title", "")) or _first_line(str(state.get("idea", ""))),
        goal=str(spec.get("goal", "")),
        features=[str(f) for f in spec.get("features", [])],
        phase=str(state.get("phase", "unknown")),
        passed=bool(acceptance.get("passed")) if acceptance else False,
        checks_passed=sum(1 for c in checks if c.get("passed")),
        checks_total=len(checks),
        groups=_group_checks(checks, spec, lang),
        console_errors=[str(e) for e in acceptance.get("console_errors", [])] if acceptance else [],
        warnings=[localize_warning(str(w), lang) for w in warnings],
        attempts=list(state.get("attempts", [])),
        planner=state.get("planner"),
        cost_usd=state.get("cost_usd"),
        error=state.get("error"),
        screenshot=screenshot if screenshot.is_file() else None,
        started_at=str(state.get("started_at", "")),
        updated_at=str(state.get("updated_at", "")),
        revision=int(state.get("revision") or 0),
        changes=[str(c) for c in state.get("changes", [])],
        tokens=state.get("tokens"),
        lang=lang,
    )
    # Older runs have no per-attempt records; rebuild a minimal list from logs.
    if not summary.attempts:
        summary.attempts = _attempts_from_logs(internal, state)
    return summary


# ------------------------------------------------------------------ grouping

_STATIC_LABELS = {
    "offline_only": "Makes no network requests",
    "testid_contract": "Every element the tests need is on the page",
    "browser_available": "A browser was available to test with",
    "browser_run": "The page loaded and the test script ran",
    "browser_result": "The test script reported back",
    "screenshot": "A screenshot was taken",
}


def _group_checks(
    checks: list[dict[str, Any]], spec: dict[str, Any], lang: str = "en"
) -> list[CheckGroup]:
    static = CheckGroup(tr("Files and safety", lang))
    by_test: dict[str, CheckGroup] = {}
    order: list[str] = []
    steps = [
        (test.get("name", ""), step)
        for test in spec.get("tests", [])
        for step in test.get("steps", [])
    ]
    step_index = 0
    for check in checks:
        name = str(check.get("name", ""))
        passed = bool(check.get("passed"))
        detail = str(check.get("detail", ""))
        if name.startswith("required_file:"):
            file = name.split(":", 1)[1]
            static.lines.append(CheckLine(name, passed, detail, tr("{file} exists", lang, file=file)))
            continue
        if name in _STATIC_LABELS or ":" not in name:
            static.lines.append(
                CheckLine(name, passed, detail, tr(_STATIC_LABELS.get(name, name), lang))
            )
            continue
        test_name, action = name.rsplit(":", 1)
        description = ""
        if step_index < len(steps) and steps[step_index][0] == test_name:
            description = describe_step(steps[step_index][1], lang)
            step_index += 1
        else:
            description = action.replace("_", " ")
        if test_name not in by_test:
            by_test[test_name] = CheckGroup(test_name)
            order.append(test_name)
        by_test[test_name].lines.append(CheckLine(name, passed, detail, description))
    groups = [static] if static.lines else []
    groups.extend(by_test[name] for name in order)
    return groups


def describe_step(step: dict[str, Any], lang: str = "en") -> str:
    """One test step in words a non-programmer can follow."""
    action = step.get("action")
    target = _target(step.get("selector"), lang)
    if action == "click":
        return tr("Click {t}", lang, t=target)
    if action == "fill":
        return tr("Type \u201c{v}\u201d into {t}", lang, v=step.get("value", ""), t=target)
    if action == "wait":
        return tr("Wait {ms} ms", lang, ms=step.get("timeout_ms", 0))
    if action == "selector_exists":
        return tr("{t} is on the page", lang, t=target)
    if action == "text_visible":
        return tr("{t} shows \u201c{e}\u201d", lang, t=target, e=step.get("expected", ""))
    if action == "attribute_equals":
        return tr(
            "{t} has {a} = \u201c{e}\u201d", lang,
            t=target, a=step.get("attribute"), e=step.get("expected", ""),
        )
    if action == "no_console_errors":
        return tr("No errors in the browser console", lang)
    return str(action)


def _target(selector: Any, lang: str = "en") -> str:
    if not isinstance(selector, str):
        return tr("the page", lang)
    start = selector.find("=")
    value = selector[start + 1:].strip("[]\"' ") if start >= 0 else selector
    return f"[{value}]"


def _attempts_from_logs(internal: Path, state: dict[str, Any]) -> list[dict[str, Any]]:
    attempts = []
    for number in range(1, int(state.get("attempt") or 0) + 1):
        router = _read_json(internal / "logs" / f"router-attempt-{number}.json") or {}
        attempts.append({"attempt": number, "executor": router.get("winner"), "outcome": None})
    return attempts


# ------------------------------------------------------------------ terminal


def render_text(summary: BuildSummary) -> str:
    lang = summary.lang
    mark = {"passed": "PASS", "failed": "FAIL"}.get(summary.verdict, summary.verdict.upper())
    lines = [
        "",
        f"  {mark}  {summary.title or 'Build'} — {summary.headline}",
        "        " + tr("{p}/{t} checks passed", lang, p=summary.checks_passed, t=summary.checks_total)
        + _attempt_phrase(summary),
    ]
    failed = [line for group in summary.groups for line in group.lines if not line.passed]
    if failed:
        lines.append("")
        lines.append("  " + tr("What failed:", lang))
        for line in failed[:8]:
            lines.append(f"    - {line.description or line.name}: {_short(line.detail, 110)}")
        if len(failed) > 8:
            lines.append("    " + tr("... and {n} more (see report.html)", lang, n=len(failed) - 8))
    if summary.warnings:
        lines.append("")
        lines.append("  " + tr("Not verified (a passing report does not cover these):", lang))
        for warning in summary.warnings[:5]:
            lines.append(f"    - {_short(warning, 120)}")
    lines.append("")
    lines.append("  " + tr("Report:  ", lang) + str(summary.project_dir / REPORT_NAME))
    if summary.verdict == "passed":
        lines.append("  " + tr("Site:    ", lang) + str(summary.project_dir / "index.html"))
    lines.append("  " + tr("Next:    ", lang) + summary.next_step())
    return "\n".join(lines)


def _attempt_phrase(summary: BuildSummary) -> str:
    lang = summary.lang
    tried = [a for a in summary.attempts if a.get("outcome") not in {None, "running"}]
    if not tried:
        return ""
    writers = []
    for attempt in tried:
        name = attempt.get("executor")
        if name and name not in writers:
            writers.append(name)
    key = "{n} attempt" if len(tried) == 1 else "{n} attempts"
    phrase = " · " + tr(key, lang, n=len(tried))
    if writers:
        phrase += " · " + tr("written by {w}", lang, w=", ".join(writers))
    if summary.cost_usd:
        phrase += f" · ${summary.cost_usd:.2f}"
    if summary.tokens:
        phrase += " · " + tr("{n} tokens", lang, n=f"{summary.tokens:,}")
    return phrase


# ------------------------------------------------------------------ markdown


def render_markdown(summary: BuildSummary, screenshot_url: str | None = None) -> str:
    icon = {"passed": "✅", "failed": "❌"}.get(summary.verdict, "⏸️")
    out = [
        f"### {icon} {summary.title or 'Rainbow Octopus build'} — {summary.headline}",
        "",
        "**" + tr("{p}/{t} checks passed", summary.lang, p=summary.checks_passed, t=summary.checks_total)
        + "**" + _attempt_phrase(summary),
        "",
    ]
    if summary.idea:
        out += [f"> {_first_line(summary.idea)}", ""]
    if screenshot_url and summary.screenshot:
        out += [f"![screenshot]({screenshot_url})", ""]
    if summary.features:
        out.append("**" + tr("What it does", summary.lang) + "**")
        out += [f"- {feature}" for feature in summary.features]
        out.append("")
    failed = [line for group in summary.groups for line in group.lines if not line.passed]
    if failed:
        out.append("**" + tr("What failed", summary.lang) + "**")
        out += [
            f"- {line.description or line.name} — `{_short(line.detail, 140)}`"
            for line in failed[:15]
        ]
        out.append("")
    if summary.warnings:
        out.append(tr("Not verified — a passing report does not cover these:", summary.lang))
        out += [f"- {warning}" for warning in summary.warnings]
        out.append("")
    out.append("<details><summary>" + tr("Every check", summary.lang) + "</summary>")
    out.append("")
    for group in summary.groups:
        out.append(f"**{group.title}**")
        out.append("")
        for line in group.lines:
            out.append(f"- {'✅' if line.passed else '❌'} {line.description or line.name}")
        out.append("")
    out.append("</details>")
    out.append("")
    out.append(f"<sub>Rainbow Octopus {__version__} · planner: {summary.planner or '-'}</sub>")
    return "\n".join(out)


# ---------------------------------------------------------------------- html


def write_html_report(project_dir: Path) -> Path:
    summary = collect(Path(project_dir))
    target = Path(project_dir) / REPORT_NAME
    target.write_text(render_html(summary), encoding="utf-8")
    return target


def render_html(summary: BuildSummary) -> str:
    verdict = summary.verdict
    lang = summary.lang
    L = lambda text, **kw: escape(tr(text, lang, **kw))  # noqa: E731
    tone = {"passed": "good", "failed": "bad"}.get(verdict, "warn")
    screenshot = ""
    if summary.screenshot:
        try:
            data = base64.b64encode(summary.screenshot.read_bytes()).decode("ascii")
            screenshot = (
                f'<figure class="shot"><img alt="Screenshot of the generated page" '
                f'src="data:image/png;base64,{data}"></figure>'
            )
        except OSError:
            screenshot = ""

    groups_html = []
    for group in summary.groups:
        rows = "".join(
            f'<li class="{"ok" if line.passed else "no"}">'
            f'<span class="mark" aria-label="{"passed" if line.passed else "failed"}">'
            f'{"✓" if line.passed else "✗"}</span>'
            f'<span class="what">{escape(line.description or line.name)}</span>'
            f'<span class="detail">{escape(_short(line.detail, 300))}</span></li>'
            for line in group.lines
        )
        state = "ok" if group.passed else "no"
        groups_html.append(
            f'<section class="group {state}"><h3>{escape(group.title)}</h3>'
            f'<ul class="checks">{rows}</ul></section>'
        )

    attempts_html = "".join(
        "<tr>"
        f"<td>#{escape(str(a.get('attempt', '')))}</td>"
        f"<td>{escape(str(a.get('executor') or '—'))}</td>"
        f"<td>{escape(tr(_outcome_label(a.get('outcome')), lang))}</td>"
        f"<td>{_checks_cell(a)}</td>"
        f"<td>{_seconds(a.get('seconds'))}</td>"
        f"<td>{_money(a.get('cost_usd'))}</td>"
        "</tr>"
        for a in summary.attempts
    )

    warnings_html = ""
    if summary.warnings:
        items = "".join(f"<li>{escape(w)}</li>" for w in summary.warnings)
        warnings_html = (
            '<section class="card notice"><h2>' + L("Not verified") + "</h2>"
            "<p>" + L("These parts of the page were never observed changing, so a pass does not prove they work.") + "</p>"
            f"<ul>{items}</ul></section>"
        )

    features_html = ""
    if summary.features:
        items = "".join(f"<li>{escape(f)}</li>" for f in summary.features)
        features_html = f'<section class="card"><h2>{L("What it should do")}</h2><ul>{items}</ul></section>'

    changes_html = ""
    if summary.changes:
        items = "".join(f"<li>{escape(c)}</li>" for c in summary.changes)
        changes_html = (
            f'<section class="card"><h2>{L("Changes applied (revision {n})", n=summary.revision)}</h2>'
            f"<ol>{items}</ol></section>"
        )

    error_html = ""
    if summary.error:
        error_html = (
            '<section class="card"><h2>' + L("Last problem") + "</h2>"
            f"<pre>{escape(_short(summary.error, 4000))}</pre></section>"
        )

    console_html = ""
    if summary.console_errors:
        items = "".join(f"<li><code>{escape(e)}</code></li>" for e in summary.console_errors)
        console_html = f'<section class="card"><h2>{L("Browser console errors")}</h2><ul>{items}</ul></section>'

    open_site = (
        f'<a class="button" href="index.html">{L("Open the page")}</a>'
        if (summary.project_dir / "index.html").is_file() else ""
    )
    meta = " · ".join(
        part for part in (
            tr("{p}/{t} checks passed", lang, p=summary.checks_passed, t=summary.checks_total),
            tr("planner: {p}", lang, p=summary.planner) if summary.planner else "",
            tr("spent ${c}", lang, c=f"{summary.cost_usd:.2f}") if summary.cost_usd else "",
            tr("{n} tokens", lang, n=f"{summary.tokens:,}") if summary.tokens else "",
            tr("updated {u} UTC", lang, u=summary.updated_at[:19].replace("T", " ")) if summary.updated_at else "",
        ) if part
    )
    return _HTML.format(
        title=escape(summary.title or "Rainbow Octopus build"),
        tone=tone,
        headline=escape(summary.headline),
        idea=escape(summary.idea),
        goal=escape(summary.goal),
        meta=escape(meta),
        open_site=open_site,
        next_step=escape(summary.next_step()),
        screenshot=screenshot,
        features=features_html,
        changes=changes_html,
        warnings=warnings_html,
        error=error_html,
        console=console_html,
        groups="".join(groups_html) or f"<p>{L('No checks have run yet.')}</p>",
        attempts=attempts_html or f'<tr><td colspan="6">{L("No attempts yet.")}</td></tr>',
        lang_attr="zh-CN" if lang == "zh" else "en",
        l_eyebrow=L("Rainbow Octopus build report"),
        l_next=L("Next:"),
        l_goal=L("Goal"),
        l_checked=L("What was checked"),
        l_attempts=L("Attempts"),
        l_th="".join(f"<th>{L(h)}</th>" for h in ("Attempt", "Written by", "Result", "Checks", "Time", "Cost")),
        l_footer=L("Generated by Rainbow Octopus {v}. This page works offline.", v=__version__),
    )


def _outcome_label(outcome: Any) -> str:
    return {
        "passed": "passed",
        "verification_failed": "checks failed",
        "execution_failed": "could not write the site",
        "executed": "written, not yet checked",
        "running": "running",
        "interrupted": "interrupted",
        "crashed": "internal error",
    }.get(str(outcome), str(outcome or "—"))


def _checks_cell(attempt: dict[str, Any]) -> str:
    total = attempt.get("checks_total")
    if not total:
        return "—"
    return f"{attempt.get('checks_passed', 0)}/{total}"


def _seconds(value: Any) -> str:
    return f"{value:.0f}s" if isinstance(value, (int, float)) else "—"


def _money(value: Any) -> str:
    return f"${value:.2f}" if isinstance(value, (int, float)) else "—"


def _short(text: str, limit: int) -> str:
    text = " ".join(str(text).split())
    return text if len(text) <= limit else text[: limit - 1] + "…"


def _first_line(text: str) -> str:
    return text.strip().splitlines()[0] if text.strip() else ""


def _quote_path(path: Path) -> str:
    text = str(path)
    return f'"{text}"' if " " in text else text


def _read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


_HTML = """<!doctype html>
<html lang="{lang_attr}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — build report</title>
<style>
:root {{
  --bg: #f6f5f2; --panel: #ffffff; --ink: #1d1d1f; --muted: #6b6b70;
  --line: #e4e2dc; --good: #1f7a4d; --good-bg: #e6f4ec; --bad: #b3261e;
  --bad-bg: #fbe9e7; --warn: #8a5a00; --warn-bg: #fdf3dc; --accent: #3b5bdb;
}}
@media (prefers-color-scheme: dark) {{
  :root {{
    --bg: #141416; --panel: #1d1d20; --ink: #ececef; --muted: #9c9ca3;
    --line: #2e2e33; --good: #5fd19b; --good-bg: #16301f; --bad: #ff8a80;
    --bad-bg: #3a1714; --warn: #f3c669; --warn-bg: #33280f; --accent: #8fa8ff;
  }}
}}
* {{ box-sizing: border-box; }}
body {{ margin: 0; background: var(--bg); color: var(--ink);
  font: 15px/1.55 system-ui, -apple-system, "Segoe UI", "PingFang SC",
  "Microsoft YaHei", sans-serif; }}
main {{ max-width: 980px; margin: 0 auto; padding: 32px 16px 64px; }}
header.verdict {{ border-radius: 14px; padding: 22px 24px; margin-bottom: 20px;
  border: 1px solid var(--line); background: var(--panel); }}
header.good {{ background: var(--good-bg); border-color: transparent; }}
header.bad {{ background: var(--bad-bg); border-color: transparent; }}
header.warn {{ background: var(--warn-bg); border-color: transparent; }}
.eyebrow {{ font-size: 13px; color: var(--muted); letter-spacing: .02em; }}
h1 {{ margin: 4px 0 6px; font-size: 26px; line-height: 1.25; }}
header.good h1 {{ color: var(--good); }}
header.bad h1 {{ color: var(--bad); }}
header.warn h1 {{ color: var(--warn); }}
.idea {{ margin: 0 0 10px; font-size: 16px; }}
.meta {{ color: var(--muted); font-size: 13px; }}
.actions {{ display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin-top: 14px; }}
.button {{ display: inline-block; padding: 8px 14px; border-radius: 8px;
  background: var(--accent); color: #fff; text-decoration: none; font-weight: 600; }}
code, pre {{ font-family: ui-monospace, "SF Mono", Consolas, monospace; font-size: 13px; }}
.next code {{ background: var(--panel); border: 1px solid var(--line); padding: 3px 8px;
  border-radius: 6px; word-break: break-all; }}
.shot {{ margin: 0 0 20px; border: 1px solid var(--line); border-radius: 12px;
  overflow: hidden; background: var(--panel); }}
.shot img {{ display: block; width: 100%; height: auto; }}
.grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }}
@media (max-width: 720px) {{ .grid {{ grid-template-columns: 1fr; }} h1 {{ font-size: 22px; }} }}
.card {{ background: var(--panel); border: 1px solid var(--line); border-radius: 12px;
  padding: 16px 18px; margin-bottom: 16px; }}
.card h2 {{ margin: 0 0 8px; font-size: 16px; }}
.card ul, .card ol {{ margin: 0; padding-left: 20px; }}
.notice {{ background: var(--warn-bg); border-color: transparent; }}
.notice h2 {{ color: var(--warn); }}
pre {{ white-space: pre-wrap; word-break: break-word; margin: 0; }}
h2.section {{ font-size: 18px; margin: 28px 0 10px; }}
.group {{ background: var(--panel); border: 1px solid var(--line); border-radius: 12px;
  padding: 12px 16px; margin-bottom: 12px; }}
.group h3 {{ margin: 0 0 6px; font-size: 15px; }}
.group.no h3 {{ color: var(--bad); }}
.checks {{ list-style: none; margin: 0; padding: 0; }}
.checks li {{ display: grid; grid-template-columns: 22px minmax(0, 1fr) minmax(0, 1fr);
  gap: 8px; padding: 6px 0; border-top: 1px solid var(--line); }}
.checks li:first-child {{ border-top: 0; }}
.checks .mark {{ font-weight: 700; }}
.checks li.ok .mark {{ color: var(--good); }}
.checks li.no .mark {{ color: var(--bad); }}
.checks li.no .what {{ font-weight: 600; }}
.checks .detail {{ color: var(--muted); font-size: 13px; overflow-wrap: anywhere; }}
@media (max-width: 720px) {{ .checks li {{ grid-template-columns: 22px 1fr; }}
  .checks .detail {{ grid-column: 2; }} }}
.table-wrap {{ overflow-x: auto; }}
table {{ width: 100%; border-collapse: collapse; background: var(--panel);
  border: 1px solid var(--line); border-radius: 12px; overflow: hidden; }}
th, td {{ text-align: left; padding: 8px 12px; border-top: 1px solid var(--line);
  font-size: 14px; white-space: nowrap; }}
th {{ color: var(--muted); font-weight: 600; border-top: 0; }}
footer {{ margin-top: 32px; color: var(--muted); font-size: 12px; }}
</style>
</head>
<body>
<main>
<header class="verdict {tone}">
  <div class="eyebrow">{l_eyebrow}</div>
  <h1>{headline}</h1>
  <p class="idea"><strong>{title}</strong> — {idea}</p>
  <div class="meta">{meta}</div>
  <div class="actions">{open_site}<span class="next">{l_next} <code>{next_step}</code></span></div>
</header>
{screenshot}
{warnings}
{error}
<div class="grid">
{features}
<section class="card"><h2>{l_goal}</h2><p>{goal}</p></section>
</div>
{changes}
{console}
<h2 class="section">{l_checked}</h2>
{groups}
<h2 class="section">{l_attempts}</h2>
<div class="table-wrap"><table>
<thead><tr>{l_th}</tr></thead>
<tbody>{attempts}</tbody>
</table></div>
<footer>{l_footer}</footer>
</main>
</body>
</html>
"""
