<#
    Removes throwaway artifacts from the repo root.

    Everything deleted here is either regenerated by a build/test run or is a
    record of a failed experiment that has already been written up in
    docs/KNOWN_ISSUES.md. Nothing under src/, tests/, docs/ or scripts/ is
    touched, and the successful demo run is kept.

    Usage:
        powershell -ExecutionPolicy Bypass -File scripts\clean.ps1
        powershell -ExecutionPolicy Bypass -File scripts\clean.ps1 -WhatIf
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [switch]$KeepDemoOutput
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

Write-Host "Cleaning $root" -ForegroundColor Cyan

$targets = @(
    # 39 MB of Edge profile left over from KI-001 debugging, incl. a 28 MB crash dump
    'work\edge-profile-test',
    # 21 MB throwaway venv used for the clean-install check
    '.venv-test',
    # setuptools intermediates
    'build',
    'src\rainbow_octopus.egg-info',
    # superseded by DECISIONS.md
    '项目决策记录.md',
    # leftover from the headless experiment
    '.claude\worktrees'
)

if (-not $KeepDemoOutput) {
    # Failed Codex smoke runs. Their logs are already quoted in KNOWN_ISSUES.md.
    # demo-output\pomodoro-1 (the first successful build) is deliberately kept.
    $targets += @(
        'demo-output\codex-smoke',
        'demo-output\codex-smoke-2',
        'demo-output\codex-smoke-4',
        'demo-output\codex-smoke-5',
        'demo-output\codex-smoke-3.stdout.log',
        'demo-output\codex-smoke-3.stderr.log',
        'demo-output\no-key-test'
    )
}

$freed = 0
foreach ($target in $targets) {
    if (-not (Test-Path $target)) { continue }
    $size = (Get-ChildItem $target -Recurse -Force -ErrorAction SilentlyContinue |
             Measure-Object -Property Length -Sum).Sum
    if ($PSCmdlet.ShouldProcess($target, 'Remove')) {
        Remove-Item $target -Recurse -Force -ErrorAction SilentlyContinue
        $freed += [int]$size
        Write-Host ("  removed  {0,-40} {1,8:N1} MB" -f $target, ($size / 1MB))
    }
}

# Stale wheels: only the current version should stay in dist\.
Get-ChildItem 'dist' -Filter '*.old' -ErrorAction SilentlyContinue | ForEach-Object {
    if ($PSCmdlet.ShouldProcess($_.Name, 'Remove stale wheel')) {
        Remove-Item $_.FullName -Force
        Write-Host "  removed  $($_.Name)"
    }
}

Get-ChildItem -Recurse -Directory -Filter '__pycache__' -ErrorAction SilentlyContinue |
    ForEach-Object { Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue }

Write-Host ("Done. Freed roughly {0:N1} MB." -f ($freed / 1MB)) -ForegroundColor Green
Write-Host "Rebuild with:  python -m build --wheel" -ForegroundColor DarkGray
